/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database.tables;


import group18.dashboard.database.Keys;
import group18.dashboard.database.Public;
import group18.dashboard.database.tables.records.CampaignRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Campaign extends TableImpl<CampaignRecord> {

    private static final long serialVersionUID = 616030275;

    /**
     * The reference instance of <code>PUBLIC.CAMPAIGN</code>
     */
    public static final Campaign CAMPAIGN = new Campaign();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CampaignRecord> getRecordType() {
        return CampaignRecord.class;
    }

    /**
     * The column <code>PUBLIC.CAMPAIGN.CID</code>.
     */
    public final TableField<CampaignRecord, Integer> CID = createField(DSL.name("CID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.CAMPAIGN.CNAME</code>.
     */
    public final TableField<CampaignRecord, String> CNAME = createField(DSL.name("CNAME"), org.jooq.impl.SQLDataType.VARCHAR(2147483647), this, "");

    /**
     * Create a <code>PUBLIC.CAMPAIGN</code> table reference
     */
    public Campaign() {
        this(DSL.name("CAMPAIGN"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CAMPAIGN</code> table reference
     */
    public Campaign(String alias) {
        this(DSL.name(alias), CAMPAIGN);
    }

    /**
     * Create an aliased <code>PUBLIC.CAMPAIGN</code> table reference
     */
    public Campaign(Name alias) {
        this(alias, CAMPAIGN);
    }

    private Campaign(Name alias, Table<CampaignRecord> aliased) {
        this(alias, aliased, null);
    }

    private Campaign(Name alias, Table<CampaignRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Campaign(Table<O> child, ForeignKey<O, CampaignRecord> key) {
        super(child, key, CAMPAIGN);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<CampaignRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CAMPAIGN;
    }

    @Override
    public UniqueKey<CampaignRecord> getPrimaryKey() {
        return Keys.CAMPAIGN_PK;
    }

    @Override
    public List<UniqueKey<CampaignRecord>> getKeys() {
        return Arrays.<UniqueKey<CampaignRecord>>asList(Keys.CAMPAIGN_PK);
    }

    @Override
    public Campaign as(String alias) {
        return new Campaign(DSL.name(alias), this);
    }

    @Override
    public Campaign as(Name alias) {
        return new Campaign(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Campaign rename(String name) {
        return new Campaign(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Campaign rename(Name name) {
        return new Campaign(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
