/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database.tables.records;


import group18.dashboard.database.tables.Campaign;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampaignRecord extends UpdatableRecordImpl<CampaignRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -863545182;

    /**
     * Setter for <code>PUBLIC.CAMPAIGN.CID</code>.
     */
    public void setCid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CAMPAIGN.CID</code>.
     */
    public Integer getCid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CAMPAIGN.CNAME</code>.
     */
    public void setCname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CAMPAIGN.CNAME</code>.
     */
    public String getCname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Campaign.CAMPAIGN.CID;
    }

    @Override
    public Field<String> field2() {
        return Campaign.CAMPAIGN.CNAME;
    }

    @Override
    public Integer component1() {
        return getCid();
    }

    @Override
    public String component2() {
        return getCname();
    }

    @Override
    public Integer value1() {
        return getCid();
    }

    @Override
    public String value2() {
        return getCname();
    }

    @Override
    public CampaignRecord value1(Integer value) {
        setCid(value);
        return this;
    }

    @Override
    public CampaignRecord value2(String value) {
        setCname(value);
        return this;
    }

    @Override
    public CampaignRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CampaignRecord
     */
    public CampaignRecord() {
        super(Campaign.CAMPAIGN);
    }

    /**
     * Create a detached, initialised CampaignRecord
     */
    public CampaignRecord(Integer cid, String cname) {
        super(Campaign.CAMPAIGN);

        set(0, cid);
        set(1, cname);
    }
}
