/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database.tables.records;


import group18.dashboard.database.tables.Interaction;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InteractionRecord extends UpdatableRecordImpl<InteractionRecord> implements Record7<LocalDateTime, Long, LocalDateTime, Integer, Boolean, Integer, Integer> {

    private static final long serialVersionUID = 1113060470;

    /**
     * Setter for <code>PUBLIC.INTERACTION.ENTRY_DATE</code>.
     */
    public void setEntryDate(LocalDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.INTERACTION.ENTRY_DATE</code>.
     */
    public LocalDateTime getEntryDate() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>PUBLIC.INTERACTION.USER</code>.
     */
    public void setUser(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.INTERACTION.USER</code>.
     */
    public Long getUser() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.INTERACTION.EXIT_DATE</code>.
     */
    public void setExitDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.INTERACTION.EXIT_DATE</code>.
     */
    public LocalDateTime getExitDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>PUBLIC.INTERACTION.VIEWS</code>.
     */
    public void setViews(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.INTERACTION.VIEWS</code>.
     */
    public Integer getViews() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.INTERACTION.CONVERSION</code>.
     */
    public void setConversion(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.INTERACTION.CONVERSION</code>.
     */
    public Boolean getConversion() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>PUBLIC.INTERACTION.CID</code>.
     */
    public void setCid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.INTERACTION.CID</code>.
     */
    public Integer getCid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>PUBLIC.INTERACTION.INTERACTIONID</code>.
     */
    public void setInteractionid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.INTERACTION.INTERACTIONID</code>.
     */
    public Integer getInteractionid() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<LocalDateTime, Long, LocalDateTime, Integer, Boolean, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<LocalDateTime, Long, LocalDateTime, Integer, Boolean, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<LocalDateTime> field1() {
        return Interaction.INTERACTION.ENTRY_DATE;
    }

    @Override
    public Field<Long> field2() {
        return Interaction.INTERACTION.USER;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Interaction.INTERACTION.EXIT_DATE;
    }

    @Override
    public Field<Integer> field4() {
        return Interaction.INTERACTION.VIEWS;
    }

    @Override
    public Field<Boolean> field5() {
        return Interaction.INTERACTION.CONVERSION;
    }

    @Override
    public Field<Integer> field6() {
        return Interaction.INTERACTION.CID;
    }

    @Override
    public Field<Integer> field7() {
        return Interaction.INTERACTION.INTERACTIONID;
    }

    @Override
    public LocalDateTime component1() {
        return getEntryDate();
    }

    @Override
    public Long component2() {
        return getUser();
    }

    @Override
    public LocalDateTime component3() {
        return getExitDate();
    }

    @Override
    public Integer component4() {
        return getViews();
    }

    @Override
    public Boolean component5() {
        return getConversion();
    }

    @Override
    public Integer component6() {
        return getCid();
    }

    @Override
    public Integer component7() {
        return getInteractionid();
    }

    @Override
    public LocalDateTime value1() {
        return getEntryDate();
    }

    @Override
    public Long value2() {
        return getUser();
    }

    @Override
    public LocalDateTime value3() {
        return getExitDate();
    }

    @Override
    public Integer value4() {
        return getViews();
    }

    @Override
    public Boolean value5() {
        return getConversion();
    }

    @Override
    public Integer value6() {
        return getCid();
    }

    @Override
    public Integer value7() {
        return getInteractionid();
    }

    @Override
    public InteractionRecord value1(LocalDateTime value) {
        setEntryDate(value);
        return this;
    }

    @Override
    public InteractionRecord value2(Long value) {
        setUser(value);
        return this;
    }

    @Override
    public InteractionRecord value3(LocalDateTime value) {
        setExitDate(value);
        return this;
    }

    @Override
    public InteractionRecord value4(Integer value) {
        setViews(value);
        return this;
    }

    @Override
    public InteractionRecord value5(Boolean value) {
        setConversion(value);
        return this;
    }

    @Override
    public InteractionRecord value6(Integer value) {
        setCid(value);
        return this;
    }

    @Override
    public InteractionRecord value7(Integer value) {
        setInteractionid(value);
        return this;
    }

    @Override
    public InteractionRecord values(LocalDateTime value1, Long value2, LocalDateTime value3, Integer value4, Boolean value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InteractionRecord
     */
    public InteractionRecord() {
        super(Interaction.INTERACTION);
    }

    /**
     * Create a detached, initialised InteractionRecord
     */
    public InteractionRecord(LocalDateTime entryDate, Long user, LocalDateTime exitDate, Integer views, Boolean conversion, Integer cid, Integer interactionid) {
        super(Interaction.INTERACTION);

        set(0, entryDate);
        set(1, user);
        set(2, exitDate);
        set(3, views);
        set(4, conversion);
        set(5, cid);
        set(6, interactionid);
    }
}
