/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database.tables.records;


import group18.dashboard.database.tables.User;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record4<Integer, String, byte[], byte[]> {

    private static final long serialVersionUID = -1920166012;

    /**
     * Setter for <code>PUBLIC.USER.UID</code>.
     */
    public void setUid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.USER.UID</code>.
     */
    public Integer getUid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.USER.USERNAME</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.USER.USERNAME</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.USER.PASSWORD</code>.
     */
    public void setPassword(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.USER.PASSWORD</code>.
     */
    public byte[] getPassword() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>PUBLIC.USER.SALT</code>.
     */
    public void setSalt(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.USER.SALT</code>.
     */
    public byte[] getSalt() {
        return (byte[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, byte[], byte[]> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, byte[], byte[]> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.UID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.USERNAME;
    }

    @Override
    public Field<byte[]> field3() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<byte[]> field4() {
        return User.USER.SALT;
    }

    @Override
    public Integer component1() {
        return getUid();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public byte[] component3() {
        return getPassword();
    }

    @Override
    public byte[] component4() {
        return getSalt();
    }

    @Override
    public Integer value1() {
        return getUid();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public byte[] value3() {
        return getPassword();
    }

    @Override
    public byte[] value4() {
        return getSalt();
    }

    @Override
    public UserRecord value1(Integer value) {
        setUid(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord value3(byte[] value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value4(byte[] value) {
        setSalt(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, byte[] value3, byte[] value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer uid, String username, byte[] password, byte[] salt) {
        super(User.USER);

        set(0, uid);
        set(1, username);
        set(2, password);
        set(3, salt);
    }
}
