/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ImpressionAge implements EnumType {

    _3c25("<25"),

    _25_34("25-34"),

    _35_44("35-44"),

    _45_54("45-54"),

    _3e54(">54");

    private final String literal;

    private ImpressionAge(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "IMPRESSION_AGE";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
