/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ImpressionGender implements EnumType {

    Male("Male"),

    Female("Female");

    private final String literal;

    private ImpressionGender(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "IMPRESSION_GENDER";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
