/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database;


import group18.dashboard.database.tables.Impression;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERINDEX = Indexes0.USERINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USERINDEX = Internal.createIndex("USERINDEX", Impression.IMPRESSION, new OrderField[] { Impression.IMPRESSION.USER }, false);
    }
}
