/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database;


import group18.dashboard.database.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_USERNAME_UINDEX = Indexes0.USER_USERNAME_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USER_USERNAME_UINDEX = Internal.createIndex("USER_USERNAME_UINDEX", User.USER, new OrderField[] { User.USER.USERNAME }, true);
    }
}
