/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database;


import group18.dashboard.database.tables.Campaign;
import group18.dashboard.database.tables.Click;
import group18.dashboard.database.tables.Impression;
import group18.dashboard.database.tables.Interaction;
import group18.dashboard.database.tables.records.CampaignRecord;
import group18.dashboard.database.tables.records.ClickRecord;
import group18.dashboard.database.tables.records.ImpressionRecord;
import group18.dashboard.database.tables.records.InteractionRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CampaignRecord, Integer> IDENTITY_CAMPAIGN = Identities0.IDENTITY_CAMPAIGN;
    public static final Identity<ClickRecord, Integer> IDENTITY_CLICK = Identities0.IDENTITY_CLICK;
    public static final Identity<ImpressionRecord, Integer> IDENTITY_IMPRESSION = Identities0.IDENTITY_IMPRESSION;
    public static final Identity<InteractionRecord, Integer> IDENTITY_INTERACTION = Identities0.IDENTITY_INTERACTION;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CampaignRecord> CAMPAIGN_PK = UniqueKeys0.CAMPAIGN_PK;
    public static final UniqueKey<ClickRecord> UNIQUECLICK = UniqueKeys0.UNIQUECLICK;
    public static final UniqueKey<ClickRecord> CLICK_PK = UniqueKeys0.CLICK_PK;
    public static final UniqueKey<ImpressionRecord> IMPRESSION_PK = UniqueKeys0.IMPRESSION_PK;
    public static final UniqueKey<InteractionRecord> UNIQUEINTERACTION = UniqueKeys0.UNIQUEINTERACTION;
    public static final UniqueKey<InteractionRecord> INTERACTION_PK = UniqueKeys0.INTERACTION_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ClickRecord, CampaignRecord> CLICK_CAMPAIGN_CID_FK = ForeignKeys0.CLICK_CAMPAIGN_CID_FK;
    public static final ForeignKey<ImpressionRecord, CampaignRecord> IMPRESSION_CAMPAIGN_CID_FK = ForeignKeys0.IMPRESSION_CAMPAIGN_CID_FK;
    public static final ForeignKey<InteractionRecord, CampaignRecord> INTERACTION_CAMPAIGN_CID_FK = ForeignKeys0.INTERACTION_CAMPAIGN_CID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CampaignRecord, Integer> IDENTITY_CAMPAIGN = Internal.createIdentity(Campaign.CAMPAIGN, Campaign.CAMPAIGN.CID);
        public static Identity<ClickRecord, Integer> IDENTITY_CLICK = Internal.createIdentity(Click.CLICK, Click.CLICK.CLICKID);
        public static Identity<ImpressionRecord, Integer> IDENTITY_IMPRESSION = Internal.createIdentity(Impression.IMPRESSION, Impression.IMPRESSION.IMPRESSIONID);
        public static Identity<InteractionRecord, Integer> IDENTITY_INTERACTION = Internal.createIdentity(Interaction.INTERACTION, Interaction.INTERACTION.INTERACTIONID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CampaignRecord> CAMPAIGN_PK = Internal.createUniqueKey(Campaign.CAMPAIGN, "CAMPAIGN_PK", new TableField[] { Campaign.CAMPAIGN.CID }, true);
        public static final UniqueKey<ClickRecord> UNIQUECLICK = Internal.createUniqueKey(Click.CLICK, "UNIQUECLICK", new TableField[] { Click.CLICK.DATE, Click.CLICK.USER }, true);
        public static final UniqueKey<ClickRecord> CLICK_PK = Internal.createUniqueKey(Click.CLICK, "CLICK_PK", new TableField[] { Click.CLICK.CLICKID }, true);
        public static final UniqueKey<ImpressionRecord> IMPRESSION_PK = Internal.createUniqueKey(Impression.IMPRESSION, "IMPRESSION_PK", new TableField[] { Impression.IMPRESSION.IMPRESSIONID }, true);
        public static final UniqueKey<InteractionRecord> UNIQUEINTERACTION = Internal.createUniqueKey(Interaction.INTERACTION, "UNIQUEINTERACTION", new TableField[] { Interaction.INTERACTION.ENTRY_DATE, Interaction.INTERACTION.USER }, true);
        public static final UniqueKey<InteractionRecord> INTERACTION_PK = Internal.createUniqueKey(Interaction.INTERACTION, "INTERACTION_PK", new TableField[] { Interaction.INTERACTION.INTERACTIONID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ClickRecord, CampaignRecord> CLICK_CAMPAIGN_CID_FK = Internal.createForeignKey(Keys.CAMPAIGN_PK, Click.CLICK, "CLICK_CAMPAIGN_CID_FK", new TableField[] { Click.CLICK.CID }, true);
        public static final ForeignKey<ImpressionRecord, CampaignRecord> IMPRESSION_CAMPAIGN_CID_FK = Internal.createForeignKey(Keys.CAMPAIGN_PK, Impression.IMPRESSION, "IMPRESSION_CAMPAIGN_CID_FK", new TableField[] { Impression.IMPRESSION.CID }, true);
        public static final ForeignKey<InteractionRecord, CampaignRecord> INTERACTION_CAMPAIGN_CID_FK = Internal.createForeignKey(Keys.CAMPAIGN_PK, Interaction.INTERACTION, "INTERACTION_CAMPAIGN_CID_FK", new TableField[] { Interaction.INTERACTION.CID }, true);
    }
}
