/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database;


import group18.dashboard.database.tables.Campaign;
import group18.dashboard.database.tables.Click;
import group18.dashboard.database.tables.Impression;
import group18.dashboard.database.tables.Interaction;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 335249810;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.CAMPAIGN</code>.
     */
    public final Campaign CAMPAIGN = Campaign.CAMPAIGN;

    /**
     * The table <code>PUBLIC.CLICK</code>.
     */
    public final Click CLICK = Click.CLICK;

    /**
     * The table <code>PUBLIC.IMPRESSION</code>.
     */
    public final Impression IMPRESSION = Impression.IMPRESSION;

    /**
     * The table <code>PUBLIC.INTERACTION</code>.
     */
    public final Interaction INTERACTION = Interaction.INTERACTION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Campaign.CAMPAIGN,
            Click.CLICK,
            Impression.IMPRESSION,
            Interaction.INTERACTION);
    }
}
