/*
 * This file is generated by jOOQ.
 */
package group18.dashboard.database;


import group18.dashboard.database.tables.Campaign;
import group18.dashboard.database.tables.Click;
import group18.dashboard.database.tables.Impression;
import group18.dashboard.database.tables.Interaction;
import group18.dashboard.database.tables.User;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CAMPAIGN</code>.
     */
    public static final Campaign CAMPAIGN = Campaign.CAMPAIGN;

    /**
     * The table <code>PUBLIC.CLICK</code>.
     */
    public static final Click CLICK = Click.CLICK;

    /**
     * The table <code>PUBLIC.IMPRESSION</code>.
     */
    public static final Impression IMPRESSION = Impression.IMPRESSION;

    /**
     * The table <code>PUBLIC.INTERACTION</code>.
     */
    public static final Interaction INTERACTION = Interaction.INTERACTION;

    /**
     * The table <code>PUBLIC.USER</code>.
     */
    public static final User USER = User.USER;
}
